apiVersion: apps/v1
kind: Deployment
metadata:
  name: ademirbot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ademirbot
  template:
    metadata:
      labels:
        app: ademirbot
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: ademirbot
        image: gcr.io/ademirbot-project/ademirbot
        imagePullPolicy: "Always"
        volumeMounts:
        - mountPath: /app/certs
          name: certs
        env:
        - name: AdemirAuth
          valueFrom:
            secretKeyRef:
              name: ademirauth
              key: auth
        - name: MongoServer
          valueFrom:
            secretKeyRef:
              name: mongoserver
              key: mongo
        - name: CertFile
          value: /app/certs/cert.pem
      volumes:
      - name: certs
        secret:
          secretName: certfile