name: CI/CD for GKE

on:
  push:
    branches:
      - main
      - hml

env:
  PROJECT_ID: ademirbot-project
  GKE_CLUSTER: ademirbot-cluster
  GKE_ZONE: southamerica-east1-a
  DEPLOYMENT_NAME: ademirbot-deployment
  IMAGE: ademirbot

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        project_id: ${{ env.PROJECT_ID }}
        install_components: 'gke-gcloud-auth-plugin'
      env:
        CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: ${{ secrets.GCP_CREDENTIALS }}

    - name: Configure Docker
      run: gcloud --quiet auth configure-docker

    - name: Build Docker Image
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ github.sha }} .
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ github.sha }}

    - name: Get GKE Credentials
      run: gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}

    - name: Delete Previous Deployment
      run: kubectl delete deployment ademirbot-deployment || true  # O "|| true" evita que a ação falhe se o deployment não existir

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} ademirbot=gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ github.sha }}
        kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }}
        kubectl get services -o wide
